### ISSUE TITLE
Calendar plugin research

### ISSUE THREAD

**Issue by codegoyf** [postrad/owc-2017#11]

**Comment by codegoyf** [comment]
i'm installing a few different plugins on my local wordpress install to see how they work, and get an idea of what we can offer to ConnectWC for functionality

**Comment by xordspar0** [comment]
Option 1: Google calendar iframe

<img width="339" alt="screen shot 2017-04-22 at 4 07 16 pm" src="https://cloud.githubusercontent.com/assets/2390950/25308360/e577ebde-2777-11e7-947a-ae93f60b9f31.png">
