### ISSUE TITLE
Wordpress user roles research

### ISSUE THREAD

**Issue by postrad** [postrad/owc-2017#12]
Administrator – Has access to all administrative options and features.
Editor – Can manage and publish posts. Traditionally, editors review posts submitted by contributors and then schedule them for review.
Author – Can publish their own posts when they wish.
Contributor – Can write posts but cannot publish them. Instead, they need to submit their posts for review.
Subscriber – Has basic functionality such as changing their profile and leaving comments.

http://cdn.wpbeginner.com/wp-content/uploads/2015/03/userroles.png

An infographic that illustrates the wordpress user roles for those who are more visual. :)

**Comment by remoz** [comment]
If we want to expand the roles of different users or add extra types of users, we should check out User Role Editor which is in the wordpress plugin directory. https://www.elegantthemes.com/blog/tips-tricks/control-user-roles-permissions-with-wordpress
