### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by postrad** [postrad/owc-2017#31]
Homepage and other L1s will need a card component.

Key difference between this and the hero is that these operate on a responsive grid- 3 items at large screens, break down to single item on small screens.

https://material.io/guidelines/components/cards.html

**Comment by postrad** [comment]
This pattern is accomplished with the Intro option for the Homepage template

**Comment by postrad** [comment]
Make the links look like buttons.

**Comment by codegoyf** [comment]
custom styles injected to make those links look like buttons, still need to hide the caret
